---
- name: Retrieve inventory from Ansible Automation Controller
  hosts: localhost
  gather_facts: false
  vars:
    provided_project_ids: [] # List of project IDs
    page_size: 25

  tasks:
    # Cross-platform Python-based solution
    - name: Set date range facts
      set_fact:
        two_weeks_ago: "{{ lookup('pipe', 'python3 -c \"import datetime; print((datetime.datetime.utcnow() - datetime.timedelta(days=14)).strftime(\\\"%Y-%m-%dT%H:%M:%SZ\\\"))\"') }}"
        today: "{{ lookup('pipe', 'python3 -c \"import datetime; print(datetime.datetime.utcnow().strftime(\\\"%Y-%m-%dT%H:%M:%SZ\\\"))\"') }}"

    - name: Include secrets
      ansible.builtin.include_vars: secret.yml
      ignore_errors: true

    - name: Initialize all_projects as an empty dictionary
      ansible.builtin.set_fact:
        all_projects: {}

    - name: Print out provided project IDs
      ansible.builtin.debug:
        msg: "Provided Project IDs are: {{ provided_project_ids }}"

    - name: Fail if no Project IDs are set
      ansible.builtin.fail:
        msg: "No project IDs are set! Please set the var provided_project_ids with a list of IDs."
      when: provided_project_ids | length == 0

    - name: Loop through each project ID and fetch information
      ansible.builtin.include_tasks: fetch_project_info.yml
      loop: "{{ provided_project_ids }}"
      loop_control:
       loop_var: project_id

- name: Build report with facts - Dynamic Documentation
  hosts: "{{ _hosts | default('localhost') }}"
  gather_facts: true

  tasks:
    - name: Print out var all_projects
      ansible.builtin.debug:
        var: all_projects

    - name: Template report into HTML
      ansible.builtin.include_role:
        name: "template_project"

    - name: Load report to host on AWS S3
      ansible.builtin.include_role:
        name: "build_report_s3"
      when: inventory_hostname == 'localhost'